# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
remodel = "rojo-rbx/remodel@0.11.0"
stylua = "johnnymorganz/stylua@0.15.1"
# rojo = "rojo-rbx/rojo@6.2.0"